import Audio from "#/models/audios";
import AutoGeneratedPlaylist from "#/models/autoGeneratedPlaylist";
import cron from "node-cron";

const autoGeneratedPlaylist = async () => {
  const result = await Audio.aggregate([
    { $sort: { likes: -1 } },
    {
      $sample: { size: 20},
    },
    {
      $group: {
        _id: "category",
        audios: { $push: "$$ROOT._id" },
      },
    },
  ]);
  result.map(async (item) => {
    await AutoGeneratedPlaylist.updateOne(
      {
        title: item._id,
      },
      {
        $set: { items: item.audios },
      },
      { upsert: true }
    );
  });
};
cron.schedule("0 0 * * * *", async () => {
  await autoGeneratedPlaylist();
});
