import { Model, model, models, ObjectId, Schema } from "mongoose";
export interface AutoGeneratedPlaylist {
  title: string;
  items: ObjectId[];
}

const playlistSchema = new Schema<AutoGeneratedPlaylist>(
  {
    title: {
      type: String,
      required: true,
    },

    items: {
      type: [Schema.Types.ObjectId],
      ref: "Audio",
    },
  },
  { timestamps: true }
);

const AutoGeneratedPlaylist =
  models.AutoGeneratedPlaylist ||
  model("AutoGeneratedPlaylist", playlistSchema);

export default AutoGeneratedPlaylist as Model<AutoGeneratedPlaylist>;
